/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MicrophoneCapture {
  constructor(deviceId?: string | undefined | null)
  /**
   * EMITTED sample rate — o rate de o PCM handed to STT (16000 quando o
   * resampler é active). Declare THIS to STT providers.
   */
  getSampleRate(): number
  /**
   * NATIVE hardware rate (e.g. 24000 para AirPods HFP, 48000 built-in) — para
   * diagnostics and HFP/Bluetooth-degradation detection oapenas
   */
  getNativeSampleRate(): number
  start(callback: ((err: Error | null, arg: Buffer) => any), onSpeechEnded?: (((err: Error | null, arg: boolean) => any)) | undefined | null): void
  stop(): void
}

export declare class SystemAudioCapture {
  constructor(deviceId?: string | undefined | null)
  /**
   * EMITTED sample rate — o rate de o PCM handed to STT (16000 quando o
   * resampler é active). This é o que callers precisa declare to STT providers.
   */
  getSampleRate(): number
  /**
   * NATIVE hardware sample rate (e.g. 48000) — para diagnostics and
   * HFP/Bluetooth-degradation detection oapenas Não o rate de emitted bytes.
   */
  getNativeSampleRate(): number
  start(callback: ((err: Error | null, arg: Buffer) => any), onSpeechEnded?: (((err: Error | null, arg: boolean) => any)) | undefined | null): void
  stop(): void
}

export interface AudioDeviceInfo {
  id: string
  name: string
}

/**
 * Deactivates a Dodo Payments license activation instance.
 *
 * `instance_id` — o activation instance ID (e.g. "lki_xxx") returned at activation time.
 * This é stored em o encrypted license arquivo and passed aqui to liberar o slot.
 *
 * Retorna a Promise resolving to "OK" ou "ERR:dodo:<reason>".
 * Network errors retorna "ERR:dodo:network:..." — callers deve ainda remove o local license
 * arquivo até em network failure (fail-safe: local removal sempre happens).
 */
export declare function deactivateDodoKey(licenseKey: string, instanceId: string): Promise<unknown>

/**
 * Retorna o platform-native ID de o current default saída device.
 * macOS: CoreAudio device UID. Windows: WASAPI device id (eMultimedia/eConsole role).
 * Empty string em error ou unsupported pplataforma
 *
 * JS polls this todo poucos seconds durante an active meeting; quando o valor
 * changes, main.ts recreates SystemAudioCapture então o CoreAudio Tap follows
 * o new saída rrotea Sem this, switching saída devices mid-meeting
 * (plug em headphones, trocar AirPods, rotea to virtual cable) leaves o tap
 * bound to o original device, capturing silence.
 */
export declare function getDefaultOutputDeviceId(): string

/**
 * Retorna a deterministic hardware fingerprint (SHA-256 hash de o machine UID).
 * This é used to travar license keys to a específico physical device.
 */
export declare function getHardwareId(): string

export declare function getInputDevices(): Array<AudioDeviceInfo>

export declare function getOutputDevices(): Array<AudioDeviceInfo>

/**
 * Valida an existing Dodo Payments license chave contra o live API.
 *
 * Used para periodic startup verifica to detect server-side revocations.
 * Retorna a Promise resolving to "OK", "REVOKED", ou "ERR:dodo:...".
 * Network errors retorna "ERR:dodo:network:..." então callers pode fail-open.
 */
export declare function validateDodoKey(licenseKey: string): Promise<unknown>

/**
 * Activates a Dodo Payments license chave contra o live API.
 *
 * `device_label` — primeiro 32 chars de o HWID hash; passed como o `name` campo então o
 * merchant pode correlate activations to devices em o Dodo dashboard.
 *
 * Retorna a Promise resolving to "OK:<instance_id>" em success, ou "ERR:dodo:<reason>".
 * O HTTP call executa em a libuv worker thread to prevenir blocking o Node.js evento loop.
 */
export declare function verifyDodoKey(licenseKey: string, deviceLabel: string): Promise<unknown>

/**
 * Valida a Gumroad license chave por calling o Gumroad Licenses API.
 * Retorna a Promise that resolves to "OK" em success, ou an error mensagem string em failure.
 * O HTTP call executa em a libuv worker thread to prevenir blocking o Node.js evento loop.
 */
export declare function verifyGumroadKey(licenseKey: string): Promise<unknown>
